### ISSUE TITLE
Please correct

### ISSUE THREAD

**Issue by xiaoleGun** [Miku-UI/platform_packages_apps_Settings#1]
https://github.com/Miku-UI/platform_packages_apps_Settings/blob/4e60eedc9fae96b9bc6bf28013956eb62f58ec11/res/values/miku_strings.xml#L46

Maybe this is https://github.com/Miku-UI , because this is a new version

**Comment by AmeChanRain** [comment]
Done, thanks! O(∩_∩)O

**Comment by xiaoleGun** [comment]
> https://github.com/Miku-UI/platform_packages_apps_Settings/blob/4e60eedc9fae96b9bc6bf28013956eb62f58ec11/res/values/miku_strings.xml#L46
> 
> Maybe this is https://github.com/Miku-UI , because this is a new version

and 
> https://github.com/Miku-UI/platform_packages_apps_Settings/blob/71fa5eee3221204ab127c7212e507df2bff13792/res/values-zh-rCN/miku_strings.xml#L43
>
